services:
  - type: web
    name: iform-quality-app
    runtime: docker
    repo: https://github.com/kanmantha/IFORM_DEMO_QUALITY_APP_MVC
    plan: free
    branch: main
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: iform-quality-db
          property: connectionString
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: APP_RELEASE
        value: "2026-08-16-1"
  - type: web
    name: iform-web
    runtime: docker
    repo: https://github.com/kanmantha/IFORM_DEMO_QUALITY_APP_MVC
    plan: free
    branch: main
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: iform-quality-db
          property: connectionString
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: APP_RELEASE
        value: "2026-08-16-1"

databases:
  - name: iform-quality-db
    plan: free
    databaseName: iform_quality
    user: iform_admin
